/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module gameover_7 (
    input clk,
    input rst,
    output reg [191:0] gameover
  );
  
  
  
  reg [2047:0] array;
  
  reg [191:0] go;
  
  
  always @* begin
    array[0+127-:128] = 128'h0f0e0d0c0b0a09080706050403020100;
    array[128+127-:128] = 128'h101112131415161718191a1b1c1d1e1f;
    array[256+127-:128] = 128'h2f2e2d2c2b2a29282726252423222120;
    array[384+127-:128] = 128'h303132333435363738393a3b3c3d3e3f;
    array[512+127-:128] = 128'h4f4e4d4c4b4a49484746454443424140;
    array[640+127-:128] = 128'h505152535455565758595a5b5c5d5e5f;
    array[768+127-:128] = 128'h6f6e6d6c6b6a69686766656463626160;
    array[896+127-:128] = 128'h707172737475767778797a7b7c7d7e7f;
    array[1024+127-:128] = 128'h8f8e8d8c8b8a89888786858483828180;
    array[1152+127-:128] = 128'h909192939495969798999a9b9c9d9e9f;
    array[1280+127-:128] = 128'hafaeadacabaaa9a8a7a6a5a4a3a2a1a0;
    array[1408+127-:128] = 128'hb0b1b2b3b4b5b6b7b8b9babbbcbdbebf;
    array[1536+127-:128] = 128'hcfcecdcccbcac9c8c7c6c5c4c3c2c1c0;
    array[1664+127-:128] = 128'hd0d1d2d3d4d5d6d7d8d9dadbdcdddedf;
    array[1792+127-:128] = 128'hefeeedecebeae9e8e7e6e5e4e3e2e1e0;
    array[1920+127-:128] = 128'hf0f1f2f3f4f5f6f7f8f9fafbfcfdfeff;
    go[0+7-:8] = array[640+56+7-:8];
    go[8+7-:8] = array[640+96+7-:8];
    go[16+7-:8] = array[768+40+7-:8];
    go[24+7-:8] = array[768+48+7-:8];
    go[32+7-:8] = array[768+56+7-:8];
    go[40+7-:8] = array[768+80+7-:8];
    go[48+7-:8] = array[768+88+7-:8];
    go[56+7-:8] = array[768+96+7-:8];
    go[64+7-:8] = array[896+32+7-:8];
    go[72+7-:8] = array[896+56+7-:8];
    go[80+7-:8] = array[896+72+7-:8];
    go[88+7-:8] = array[896+96+7-:8];
    go[96+7-:8] = array[1024+32+7-:8];
    go[104+7-:8] = array[1024+48+7-:8];
    go[112+7-:8] = array[1024+56+7-:8];
    go[120+7-:8] = array[1024+72+7-:8];
    go[128+7-:8] = array[1024+88+7-:8];
    go[136+7-:8] = array[1024+96+7-:8];
    go[144+7-:8] = array[1152+32+7-:8];
    go[152+7-:8] = array[1152+72+7-:8];
    go[160+7-:8] = array[1280+40+7-:8];
    go[168+7-:8] = array[1280+48+7-:8];
    go[176+7-:8] = array[1280+80+7-:8];
    go[184+7-:8] = array[1280+88+7-:8];
    gameover = go;
  end
endmodule
