/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module boole_25 (
    input [15:0] a,
    input [15:0] b,
    input [3:0] alufn,
    output reg [15:0] boole
  );
  
  
  
  always @* begin
    
    case (alufn[0+3-:4])
      default: begin
        boole = 1'h0;
      end
      4'h0: begin
        boole = 1'h0;
      end
      4'h1: begin
        boole = ~(a | b);
      end
      4'h2: begin
        boole = a & (~b);
      end
      4'h3: begin
        boole = ~b;
      end
      4'h4: begin
        boole = b & (~a);
      end
      4'h5: begin
        boole = ~a;
      end
      4'h6: begin
        boole = a ^ b;
      end
      4'h7: begin
        boole = ~(a & b);
      end
      4'h8: begin
        boole = a & b;
      end
      4'h9: begin
        boole = ~(a ^ b);
      end
      4'ha: begin
        boole = a;
      end
      4'hb: begin
        boole = a | (~b);
      end
      4'hc: begin
        boole = b;
      end
      4'hd: begin
        boole = b | (~a);
      end
      4'he: begin
        boole = a | b;
      end
      4'hf: begin
        boole = 16'hffff;
      end
    endcase
  end
endmodule
