/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module cmp_25 (
    input [1:0] alufn,
    input z,
    input v,
    input n,
    output reg [15:0] cmp
  );
  
  
  
  always @* begin
    
    case (alufn[0+1-:2])
      default: begin
        cmp[0+0-:1] = 1'h0;
      end
      2'h0: begin
        cmp[0+0-:1] = 1'h0;
      end
      2'h1: begin
        cmp[0+0-:1] = z;
      end
      2'h2: begin
        cmp[0+0-:1] = v ^ n;
      end
      2'h3: begin
        cmp[0+0-:1] = z | (v ^ n);
      end
    endcase
  end
endmodule
